### ISSUE TITLE
Add email to customised profile

### ISSUE THREAD

**Issue by eddiejaoude** [Amisha-Mohapatra/Amisha-Mohapatra#1]
- add email to customised profile
- refactor formatting

**Comment by rohan-kulkarni-25** [comment]
> * add email to customised profile
> * refactor formatting

I was looking for opening the link of LinkedIn and email profile in a new tab I searched the web but don't find do you know how to do it?

**Comment by Amisha-Mohapatra** [comment]
Right click and there will be an option for open in new tab..I think this
will work.
